version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=mongodb+srv://admin:0997951929@chat.hkfgqni.mongodb.net/test
